---
# Kubernetes control plane setup

- name: Initialize Kubernetes cluster
  shell: >
    kubeadm init 
    --pod-network-cidr=10.244.0.0/16 
    --apiserver-advertise-address={{ ansible_default_ipv4.address }}
    --ignore-preflight-errors=all
  args:
    creates: /etc/kubernetes/admin.conf
  register: kubeadm_init

- name: Create .kube directory for ansible user
  file:
    path: /home/ansible/.kube
    state: directory
    owner: ansible
    group: ansible
    mode: '0755'

- name: Copy admin.conf to ansible user's .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ansible/.kube/config
    remote_src: yes
    owner: ansible
    group: ansible
    mode: '0644'

- name: Create .kube directory for root user
  file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Copy admin.conf to root's .kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root
    mode: '0600'

- name: Install Flannel network plugin
  shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
  args:
    creates: /etc/cni/net.d/10-flannel.conflist
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: flannel_result
  until: flannel_result.rc == 0
  retries: 5
  delay: 10

- name: Generate join command for worker nodes
  shell: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  become: no
  changed_when: false