---
all:
  children:
    k8s_cluster:
      children:
        k8s_control:
          hosts:
            ubuntu1:
              ansible_host: ubuntu1
              ansible_user: ansible
        k8s_workers:
          hosts:
            ubuntu2:
              ansible_host: ubuntu2
              ansible_user: ansible
            ubuntu3:
              ansible_host: ubuntu3
              ansible_user: ansible
            centos1:
              ansible_host: centos1
              ansible_user: ansible
            centos3:
              ansible_host: centos3
              ansible_user: ansible
    monitoring:
      hosts:
        centos2:
          ansible_host: centos2
          ansible_user: ansible
    control:
      hosts:
        ubuntu-c:
          ansible_host: ubuntu-c
          ansible_user: ansible
