- name: Install prerequisites for containerd on Ubuntu
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Ensure keyring directories exist
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: Download and add Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  when: ansible_os_family == "Debian"

- name: Add Docker repository
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/docker.list
  when: ansible_os_family == "Debian"

- name: Update apt cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install containerd package
  apt:
    name: containerd
    state: present
      
- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory
        
- name: Create basic containerd configuration
  copy:
    dest: /etc/containerd/config.toml
    content: |
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          systemd_cgroup = true
    mode: '0644'